{{- if .Values.config.tika.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "james.fullname" . }}-tika
  labels:
    app: {{ template "james.name" . }}-tika
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: tika
      port: 9998
      targetPort: container
  selector:
    app: {{ template "james.name" . }}-tika
    release: {{ .Release.Name }}
{{- end }}
