version: '2'

services:
  build:
    image: ${JAMES_PROJECT_IMAGE}:latest
    build:
      context: dockerfiles/compilation/java-8
  major:
    extends: build
    image: ${JAMES_PROJECT_IMAGE}:${MAJOR}
  minor:
    extends: build
    image: ${JAMES_PROJECT_IMAGE}:${MAJOR}.${MINOR}
  patch:
    extends: build
    image: ${JAMES_PROJECT_IMAGE}:${MAJOR}.${MINOR}.${PATCH}
