{{- if .Values.config.elasticsearch.enabled }}
{{- if (and .Values.config.elasticsearch.internal .Values.config.elasticsearch.kibana) }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "james.fullname" . }}-kibana
  labels:
    app: {{ template "james.name" . }}-kibana
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "james.name" . }}-kibana
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "james.fullname" . }}-kibana
          image: {{ .Values.images.kibana.repository }}:{{ .Values.images.kibana.tag }}
          imagePullPolicy: {{ .Values.images.kibana.pullPolicy }}
          ports:
            - name: container
              containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://{{ template "james.fullname" . }}-elasticsearch:9200
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "james.sharedname" . }}-elasticsearch-auth
                  key: username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "james.sharedname" . }}-elasticsearch-auth
                  key: password
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
{{- end }}
{{- end }}
