apiVersion: v1
kind: Secret
metadata:
  name: {{ template "james.fullname" . }}
  labels:
    app: {{ template "james.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- $elasticsearch := .Values.config.elasticsearch }}
  elasticsearch_url: {{ $elasticsearch.url | b64enc }}
  elasticsearch_password: {{ $elasticsearch.password | b64enc }}
