{{- if .Values.config.elasticsearch.enabled }}
{{- if (and .Values.config.elasticsearch.internal (and .Values.config.elasticsearch.kibana .Values.ingress.kibana.enabled)) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "james.fullname" . }}-kibana
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.kibana.tls }}
    {{- if (empty .Values.ingress.kibana.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.kibana.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "james.name" . }}-kibana
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.kibana.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.kibana.path }}
            backend:
              serviceName: {{ template "james.fullname" . }}-kibana
              servicePort: http
  {{- if .Values.ingress.kibana.tls }}
  tls:
    - secretName: {{ template "james.kibana-certificate" . }}
      hosts:
        - {{ .Values.ingress.kibana.hostname }}
  {{- end }}
{{- end }}
{{- end }}
