{{- if .Values.config.elasticsearch.enabled }}
{{- if .Values.config.elasticsearch.internal }}
apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: {{ template "james.fullname" . }}-elasticsearch
  labels:
    app: {{ template "james.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  version: {{ .Values.config.elasticsearch.version | quote }}
  configSource:
    configMap:
      name: {{ template "james.fullname" . }}-elasticsearch
  {{- if (not (empty .Values.persistence.backup.restore.elasticsearchSnapshot)) }}
  databaseSecret:
    secretName: {{ template "james.sharedname" . }}-elasticsearch-auth
  {{- end }}
  {{- if .Values.config.elasticsearch.prometheus }}
  monitor:
    agent: prometheus.io/builtin
  {{- end }}
  {{- if (gt (.Values.config.elasticsearch.replicas | int64) 1) }}
  replicas: {{ .Values.config.elasticsearch.replicas }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storageType: Durable
  storage:
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ''
    {{- else }}
    storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    {{- end }}
    accessModes:
      - {{ .Values.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistence.size }}
  {{- else }}
  storageType: Ephemeral
  {{- end }}
  serviceTemplate:
    metadata:
      annotations:
        passMe: ToService
    spec:
      type: {{ .Values.service.elasticsearch.type }}
      {{- if (or (eq .Values.service.elasticsearch.type "LoadBalancer") (eq .Values.service.elasticsearch.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.elasticsearch.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: elasticsearch
          port: 9200
          targetPort: elasticsearch
          {{- if (and (eq .Values.service.elasticsearch.type "NodePort") (not (empty .Values.service.elasticsearch.nodePorts.elasticsearch))) }}
          nodePort: {{ .Values.service.elasticsearch.nodePorts.elasticsearch }}
          {{- end }}
  replicaServiceTemplate:
    annotations:
      passMe: ToReplicaService
    spec:
      type: {{ .Values.service.elasticsearch.type }}
      {{- if (or (eq .Values.service.elasticsearch.type "LoadBalancer") (eq .Values.service.elasticsearch.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.elasticsearch.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: elasticsearch
          port: 9200
          targetPort: elasticsearch
          {{- if (and (eq .Values.service.elasticsearch.type "NodePort") (not (empty .Values.service.elasticsearch.nodePorts.elasticsearch))) }}
          nodePort: {{ .Values.service.elasticsearch.nodePorts.elasticsearch }}
          {{- end }}
  updateStrategy:
    type: RollingUpdate
  terminationPolicy: Delete
{{- end }}
{{- if .Values.persistence.backup.enabled }}
---
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: {{ template "james.fullname" . }}-elasticsearch
  labels:
    app: {{ template "james.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    stash.appscode.com/backup-blueprint: {{ template "james.fullname" . }}-elasticsearch
spec:
  clientConfig:
    service:
      name: {{ template "james.fullname" . }}-elasticsearch
      port: 9200
      scheme: http
  secretTransforms:
    - renameKey:
        from: ADMIN_USERNAME
        to: username
    - renameKey:
        from: ADMIN_PASSWORD
        to: password
  type: kubedb.com/elasticsearch
{{- if (not (empty .Values.persistence.backup.restore.elasticsearchSnapshot)) }}
{{- $restore := .Values.persistence.backup.restore }}
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: {{ template "james.fullname" . }}-elasticsearch
  labels:
    app: {{ template "james.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubedb.com/kind: Elasticsearch
spec:
  driver: Restic
  task:
    name: elasticsearch-restore-{{ .Values.config.elasticsearch.version }}
  repository:
    name: elasticsearch-{{ template "james.fullname" . }}-elasticsearch
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: {{ template "james.fullname" . }}-elasticsearch
  rules:
    - snapshots:
      - {{ $restore.elasticsearchSnapshot | quote }}
{{- end }}
{{- end }}
{{- end }}
